export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'zh-CN': {
    app_name: '言叶之庭',
    welcome_sub: '静下心来，开启今日修习',
    stat_streak: '连续天数', stat_total: '题库总量', stat_acc: '正确率',
    chart_title: '近期正确率走势', legend_correct: '正确', legend_wrong: '错误',
    btn_start: '进入学习', btn_resume: '继续上次进度', btn_settings: '系统设定',
    recent_title: '最近接触', no_recent: '暂无记录', cal_title: '近期活跃 (最近14天)',
    sr_title: '间隔重复记忆', sr_desc: '开启后：错题高频复现。掌握的词条今天隐身，明天重现以检验长期记忆。',
    label_groups: '选择词库', btn_all: '全选', btn_none: '全不选', btn_del_groups: '删除选中的词库',
    label_mode: '题型过滤', label_import: '导入私密数据',
    btn_resource: '浏览共享资源中心', panel_setup: '学习配置', panel_wrong: '错题本', panel_rc: '共享资源中心',
    panel_upload: '分享题库', panel_settings: '系统设定',
    btn_begin: '开 始', btn_clear_wrong: '清空记录', btn_export: '导出为文本',
    nav_back: '返回', nav_wrong: '错题', nav_hint: '提示', nav_config: '配置',
    btn_clear: '清空', btn_undo: '撤销', btn_pen: '画笔', btn_check: '核对答案', btn_skip: '跳过',
    ans_header: '核对结果', btn_wrong: '记错', btn_correct: '正确',
    btn_again: '再来一轮', btn_home: '返回首页', btn_share: '分享我的题库',
    admin_title: '邀请码管理', btn_gen_code: '生成 1 个', btn_refresh: '刷新',
    user_not_logged: '未登录', btn_logout: '退出登录', btn_delete_acc: '注销账号',
    btn_fullscreen: '开启全屏模式', label_lang: '界面语言',
    setting_bgm: '背景音乐', setting_dblclick: '双击清空画板', label_intense_time: '激烈模式限时',
    btn_custom_bank: '自定义新建题库',
    save_progress: '保存当前进度'
  },
  'en': {
    app_name: 'YanYe Study',
    welcome_sub: "Clear your mind and begin today's practice",
    stat_streak: 'Day Streak', stat_total: 'Total Cards', stat_acc: 'Accuracy',
    chart_title: 'Recent Accuracy Trend', legend_correct: 'Correct', legend_wrong: 'Wrong',
    btn_start: 'Start Study', btn_resume: 'Resume Session', btn_settings: 'Settings',
    recent_title: 'Recent', no_recent: 'No history', cal_title: 'Activity (Last 14 Days)',
    sr_title: 'Spaced Repetition', sr_desc: 'Wrong cards appear more often. Mastered cards hide today.',
    label_groups: 'Select Groups', btn_all: 'All', btn_none: 'None', btn_del_groups: 'Delete Selected',
    label_mode: 'Question Filter', label_import: 'Import Data',
    btn_resource: 'Shared Resources', panel_setup: 'Study Setup', panel_wrong: 'Wrong Cards', panel_rc: 'Shared Resources',
    panel_upload: 'Share Deck', panel_settings: 'Settings',
    btn_begin: 'Start', btn_clear_wrong: 'Clear All', btn_export: 'Export Text',
    nav_back: 'Back', nav_wrong: 'Wrongs', nav_hint: 'Hint', nav_config: 'Config',
    btn_clear: 'Clear', btn_undo: 'Undo', btn_pen: 'Pen', btn_check: 'Check Answer', btn_skip: 'Skip',
    ans_header: 'Answer', btn_wrong: 'Wrong', btn_correct: 'Correct',
    btn_again: 'Again', btn_home: 'Home', btn_share: 'Share My Deck',
    admin_title: 'Invite Codes', btn_gen_code: 'Generate', btn_refresh: 'Refresh',
    user_not_logged: 'Not logged in', btn_logout: 'Log Out', btn_delete_acc: 'Delete Account',
    btn_fullscreen: 'Fullscreen', label_lang: 'Language',
    setting_bgm: 'BGM', setting_dblclick: 'Db-click Clear', label_intense_time: 'Intense Timer',
    btn_custom_bank: 'Custom Question Bank',
    save_progress: 'Save Progress'
  }
};
